credentials:
  usernames:
    nowadays_studio:
      name: "Nowadays Studio"
      password: "$2b$12$Wq2g68LgkmgTUnx/BYYB5.HbHIvMBcqBesjlZPBPAGHcYnfqCTxXa"  # reemplaza con contrase√±a cifrada

cookie:
  name: "dashboard_cookie"
  key: "random_key_string"
  expiry_days: 30
